baseURL:  https://darktable-org.github.io/dtdocs/
defaultContentLanguage: en-us
languages:
  en-us:
    title: darktable 3.5 (dev) user manual
    weight: 1
theme:
  - hugo-darktable-docs-pdf-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    renderer:
      unsafe: true
