baseURL:  https://docs.darktable.org/usermanual/development/
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    title: darktable 4.3 (dev) user manual
    languageName: English
    weight: 1
  fr:
    title: darktable 4.3 (dev) user manual
    languageName: Français
    weight: 2
  de:
    title: darktable 4.3 (dev) user manual
    languageName: German
    weight: 4
  eo:
    title: darktable 4.3 (dev) user manual
    languageName: Esperanto
    weight: 5
  es:
    title: darktable 4.3 (dev) user manual
    languageName: Español
    weight: 6
  gl:
    title: darktable 4.3 (dev) user manual
    languageName: Galician
    weight: 7
  it:
    title: darktable 4.3 (dev) user manual
    languageName: Italian
    weight: 8
  pl:
    title: darktable 4.3 (dev) user manual
    languageName: Polish
    weight: 9
  pt_br:
    title: manual do usuário darktable 4.3 (dev)
    languageName: Português
    weight: 10
  uk:
    title: darktable 4.3 (dev) user manual
    languageName: Ukrainian
    weight: 11
  nl:
    title: darktable 4.3 (dev) user manual
    languageName: Dutch
    weight: 12
theme:
  - hugo-darktable-docs-theme
markup:
  highlight:
    style: algol_nu
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1
outputs:
  home:
    - HTML
    - RSS
    - JSON
module:
  mounts:
    - source: ./themes//hugo-darktable-docs-theme/assets/node_modules/fork-awesome/fonts
      target: static/fonts
ignoreFiles:
- \.svg$
- \.odg$
- \.xcf$
