baseURL:
defaultContentLanguage: en-us
languages:
  en-us:
    title: darktable 3.5 (dev) user manual
    languageName: English
    weight: 1
  fr-fr:
    title: darktable 3.5 (dev) user manual
    languageName: Fran√ßais
    weight: 2
  de:
    title: darktable 3.5 (dev) user manual
    languageName: German
    weight: 4
  eo:
    title: darktable 3.5 (dev) user manual
    languageName: Esperanto
    weight: 5
  es:
    title: darktable 3.5 (dev) user manual
    languageName: Espanol
    weight: 6
  gl:
    title: darktable 3.5 (dev) user manual
    languageName: Galician
    weight: 7
  it:
    title: darktable 3.5 (dev) user manual
    languageName: Italian
    weight: 8
  pl:
    title: darktable 3.5 (dev) user manual
    languageName: Polish
    weight: 9
  pt-br:
    title: darktable 3.5 (dev) user manual
    languageName: Portuguese
    weight: 10
  uk:
    title: darktable 3.5 (dev) user manual
    languageName: Ukrainian
    weight: 11
theme:
  - hugo-darktable-docs-epub-theme
markup:
  highlight:
    style: algol_nu
  goldmark:
    extensions:
      typographer: false
    renderer:
      unsafe: true
      xHTML: true

disableKinds:
  - sitemap
  - taxonomy
  - term

uglyURLs: true
relativeURLs: true

mediaTypes:
  application/xhtml+xml:
    suffixes:
      - xhtml
  application/opf+xml:
    suffixes:
      - opf
  application/x-dtbncx+xml:
    suffixes:
      - ncx

outputFormats:
  XHTML:
    mediaType: application/xhtml+xml
    isHTML: true
    permalinkable: true
    baseName: toc
  OPF:
    mediaType: application/opf+xml
    isHTML: true
    permalinkable: true
    baseName: content
  NCX:
    mediaType: application/x-dtbncx+xml
    isHTML: true
    permalinkable: true
    baseName: toc

outputs:
  page:
    - HTML
  home:
    - OPF
    - NCX
    - HTML
    - XHTML
  section:
    - HTML

params:
  description: The user manual for darktable
  creator: darktable
  author: darktable
  publisher: darktable
